[package]
name = "pm"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "argv"
harness = false

[[bench]]
name = "entrypoints"
harness = false

[[bin]]
name = "pm-trace"
path = "src/bin/pm-trace.rs"

[dependencies]
arbitrary = { version = "1.4.2", features = ["derive"] }
clap = { version = "4.6.6", features = ["derive"] }
dialoguer = "0.12.0"
either = { version = "1.18.0", features = ["serde"] }
hakoniwa = { version = "1.7.2", features = ["landlock"] }
miette = { version = "7.6.0", features = ["fancy"] }
minreq = { version = "3.0.0", features = ["https-rustls"] }
nix = { version = "0.31.3", features = ["ptrace", "process", "signal"] }
nom = "8.0.0"
rayon = "1.12.0"
regex = "1.13.1"
ring = "0.17.14"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
tempfile = "3.27.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tree-sitter = "0.27.0"
tree-sitter-bash = "0.25.1"
tree-sitter-c = "0.24.2"
tree-sitter-cpp = "0.23.4"
tree-sitter-go = "0.25.0"
tree-sitter-python = "0.25.0"
tree-sitter-rust = "0.24.2"
url = { version = "2.5.8", features = ["serde"] }
walkdir = "2.5.0"
zbus = { version = "5.19", default-features = false, features = ["async-io", "blocking-api", "p2p"] }

[dev-dependencies]
divan = "0.1.21"
proptest = "1.11.0"
